version: "3.7"

services:
  db:
    image: postgres:15
    container_name: postgres_flask_db
    ports:
      - "5432:5432"
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_app
    ports:
      - "6379:6379"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_app
    ports:
      - "5672:5672"   # Порт для обмена сообщениями
      - "15672:15672"  # Порт для UI управления
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    container_name: flask_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
        - db
        - redis
        - rabbitmq
