"""added field owner to model TradingStrategy

Revision ID: 6d669e694248
Revises: 
Create Date: 2025-01-09 13:40:32.121827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d669e694248'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trading_strategy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_strategy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('asset_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('buy_condition', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('sell_condition', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', name='tradingstatus'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='trading_strategy_pkey')
    )
    # ### end Alembic commands ###
