openapi: 3.0.0
info:
  title: Swagger Trading Manager - OpenAPI 3.0
  version: 1.0.0

servers:
  - url: http://127.0.0.1:5000/
  - url: http://0.0.0.0:5000/

paths:

  /auth/register/:
    post:
      summary: User signup
      description: Registration user with first_name, last_name, email and password
      requestBody:
        description: Signup credentials
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/register'
          application/xml:
            schema:
              $ref: '#/components/schemas/register'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/register'
        required: true
      responses:
        '200':
          description: Registration successful
        '400':
          description: Invalid credential
        '500':
          description: Server error

  /auth/login/:
    post:
      summary: User login
      description: Log in with email and password
      requestBody:
        description: Login credentials
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/login'
          application/xml:
            schema:
              $ref: '#/components/schemas/login'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/login'
        required: true
      responses:
        '200':
          description: Login successful
        '400':
          description: Invalid credential
        '404':
          description: User not found
        '500':
          description: Server error

  /auth/me/:
    get:
      summary: User info
      description: Info about current auth user
      responses:
        '200':
          description: User info
        '400':
          description: Not Authorization
        '500':
          description: Server error
      security:
        - bearerAuth: [ ]

  /strategies/:
    get:
      summary: All strategies current user
      description: All explicit strategies of the current user
      responses:
        '200':
          description: Strategies info
        '400':
          description: Not Authorization
        '500':
          description: Server error
      security:
        - bearerAuth: [ ]

    post:
      summary: Added new strategy
      description: Create new strategy with detail info
      requestBody:
        description: Strategy parameters
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/strategy_data'
        required: true
      responses:
        '200':
          description: Successful
        '400':
          description: Not Authorization
        '500':
          description: Server error
      security:
        - bearerAuth: [ ]

  /strategies/{id}/:
    get:
      summary: Information about a specific strategy.
      description: Information about a specific strategy.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Strategy identifier
      responses:
        '200':
          description: Successful
        '400':
          description: Not Authorization
        '404':
          description: Not Found
        '500':
          description: Server error
      security:
        - bearerAuth: [ ]

    put:
      summary: Update strategy
      description: Update strategy by provide data
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Strategy identifier
      requestBody:
        description: Strategy parameters
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/strategy_data'
        required: true
      responses:
        '200':
          description: Successful
        '400':
          description: Not Authorization
        '404':
          description: Not Found
        '500':
          description: Server error
      security:
        - bearerAuth: [ ]

    delete:
      summary: Delete strategy
      description: Delete strategy by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Strategy identifier
      responses:
        '200':
          description: Successful
        '400':
          description: Not Authorization
        '404':
          description: Not Found
        '500':
          description: Server error
      security:
        - bearerAuth: [ ]


components:
  schemas:
    login:
      type: object
      properties:
        email:
          type: string
          example: user123@mail.com
        password:
          type: string
          example: PASSword0987654321!


    register:
      type: object
      properties:
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Silver
        email:
          type: string
          example: user123@mail.com
        password:
          type: string
          example: PASSword0987654321!

    strategy_data:
      type: object
      properties:
        name:
          type: string
          example: Strategy to SP500
        description:
          type: string
          example: S&P 500 trading strategies have a variety of approaches, including momentum reversal, mean reversion, breakout, arbitrage, and pair trading.
        asset_type:
          type: string
          example: stock
        buy_condition:
          type: json
          example: {"indicator": "momentum", "threshold": 2.5}
        sell_condition:
          type: json
          example: { "indicator": "momentum", "threshold": -2.5 }
        status:
          type: string
          example: active


  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Defines JWT-based authentication.
